/*
 * TailwindCSS Configuration File
 *
 * Docs: https://tailwindcss.com/docs/configuration
 * Default: https://github.com/tailwindcss/tailwindcss/blob/master/stubs/defaultConfig.stub.js
 */
module.exports = {
  theme: {
    extend: {
      colors: {
        // Generated by https://javisperez.github.io/tailwindcolorshades
        primary: {
          100: '#EAFEFF',
          200: '#CBFDFF',
          300: '#ABFBFF',
          400: '#6CF8FF',
          500: '#2DF5FF',
          600: '#29DDE6',
          700: '#1B9399',
          800: '#146E73',
          900: '#0E4A4D'
        },
        secondary: {
          100: '#FFE7FA',
          200: '#FFC4F3',
          300: '#FFA1EB',
          400: '#FE5ADC',
          500: '#FE13CD',
          600: '#E511B9',
          700: '#980B7B',
          800: '#72095C',
          900: '#4C063E'
        },
        dark: {
          100: '#E8E6E8',
          200: '#C5C0C6',
          300: '#A39AA3',
          400: '#5D4F5F',
          500: '#18031A',
          600: '#160317',
          700: '#0E0210',
          800: '#0B010C',
          900: '#070108'
        }
      },
      boxShadow: (theme) => ({
        'glow-primary': `0 0 5px #2DF5FF, 0 0 10px #2DF5FF, 0 0 20px #2DF5FF`
      }),
      fontFamily: {
        cursive: ['Pacifico', 'cursive'],
        sans: ['"Source Sans Pro"', 'sans-serif']
      }
    }
  },
  variants: {},
  plugins: []
}
